using System.Collections.Generic;
using System.Globalization;

namespace Kiosk
{
    /// <summary>
    /// Screen text, never written inline in a view. Portuguese and English from
    /// the first screen; the console's own language picks the default and
    /// KIOSK_LANG overrides it when checking a translation.
    /// </summary>
    internal static class Texts
    {
        private static readonly Dictionary<string, string> Pt = new Dictionary<string, string>
        {
            { "setup.title", "Configurar" },
            { "setup.inputhint", "Aviso do modo de controle" },
            { "setup.input", "Modo de entrada ao abrir um jogo" },
            { "setup.pc", "PC — controle como mouse e teclado" },
            { "setup.controller", "Controle nativo — exige suporte do jogo" },
            { "setup.sensitivity", "Velocidade do ponteiro (0,25× a 2×)" },
            { "setup.diagnostics", "Mostrar diagnóstico sobre o jogo" },
            { "setup.on", "Ligado" },
            { "setup.off", "Desligado" },
            { "setup.save", "Aplicar" },
            { "setup.cancel", "Cancelar" },
            { "setup.applied", "Configuração aplicada." },
            { "setup.failed", "Não foi possível abrir a configuração. Tente novamente pela tela inicial." },
            { "setup.hint", "No modo PC, use o analógico direito para apontar e A para clicar. Segure View + Menu para trocar de modo durante o jogo. A compatibilidade ainda está em testes." },
            { "game.loading", "Iniciando o jogo…" },
            { "game.mode.pc", "Modo PC · Segure View + Menu para usar o controle nativo" },
            { "game.mode.controller", "Modo controle · Segure View + Menu para usar mouse e teclado" },
            { "game.loading.hint", "Preparando a camada de compatibilidade. Não é preciso apertar novamente." },
            { "game.input.hint", "Analógico direito: mouse · A: clicar/atirar · Esquerdo: mover · Y: pular" },
            { "debug.title", "Nativra {0} · {1} · pré-alpha" },
            { "debug.system", "{0}\nSistema: {1} · {2}" },
            { "debug.gpu", "GPU: {0} · PCI {1}:{2}" },
            { "debug.vram", "VRAM reportada: {0} MiB (não é orçamento)\nD3D11 · feature level 0x{1}" },
            { "debug.unknown", "não consultado" },
            { "debug.render", "Quadro: {0}×{1} · D3D11 → CPU → XAML" },
            { "debug.frames", "Present: {0}/s · XAML: {1}/s (não FPS da TV)" },
            { "debug.memory", "Memória do app: {0} / {1} MiB de limite" },
            { "debug.input", "Gamepads UWP: {0} · leituras XInput: {1} · consultas: {3}\nEventos de tecla: {2}" },
            { "debug.audio.client", "Áudio: cliente adquirido; saída não validada" },
            { "debug.audio.pending", "Áudio: cliente indisponível · HRESULT 0x{0}" },
            { "debug.sample", "Amostra: {0} · atualização 1 s" },
            { "debug.unavailable", "Diagnóstico temporariamente indisponível" },
            { "app.eyebrow", "EM DESENVOLVIMENTO  \u00B7  POR NSPXMIGUEL" },
            { "tile.allgames", "Todos os jogos \u00B7 {0}" },
            { "status.notyet", "{0} ainda n\u00E3o foi constru\u00EDdo" },
            { "dock.library", "Biblioteca" },
            { "emu.add", "P\u00F4r na biblioteca" },
            { "shop.title", "Adicionar sistemas" },
            { "shop.install", "Instalar" },
            { "shop.downloading", "Baixando\u2026" },
            { "shop.unpacking", "Descompactando\u2026" },
            { "shop.installing", "Instalando\u2026" },
            { "shop.installed", "Instalado" },
            { "shop.installed.long", "{0} instalado. Ele aparece entre os apps do console; o xbdev sync o traz para esta tela." },
            { "shop.failed", "Falhou: {0}" },
            { "shop.stuck", "Parou em {0}; veja shop-log.txt" },
            { "shop.nopackage", "o arquivo baixado n\u00E3o tem um pacote para instalar" },
            { "emu.remove", "Tirar da biblioteca" },
            { "dock.shop", "Loja" },
            { "dock.emulators", "Emuladores" },
            { "dock.friends", "Amigos" },
            { "dock.mods", "Mods" },
            { "dock.downloads", "Downloads" },
            { "app.title", "Tudo que está instalado neste console" },
            { "status.reading", "lendo o console..." },
            { "status.count", "{0} instalados" },
            { "status.empty", "nada instalado ainda — rode xbdev kit no Mac" },
            { "status.opening", "abrindo {0}..." },
            { "status.refused", "o console recusou abrir {0}" },
            { "status.failed", "não abriu {0}: {1}" },
            { "status.unreadable", "não consegui ler a lista de apps: {0}" },
            { "hint.open", "Abrir" },
            { "hint.refresh", "Atualizar" },
            { "empty.title", "Nada instalado ainda" },
            { "empty.next", "Rode xbdev sync no Mac e aperte Y aqui" },
            { "status.noprotocol", "este abre pelo Dev Home — ele não aceita ser aberto de fora" },
            { "hint.back", "Voltar" },
            { "game.install", "Instalar" },
            { "game.play", "Jogar" },
            { "game.cancel", "Cancelar" },
            { "game.where", "INSTALAR EM" },
            { "game.place.console", "Console" },
            { "game.place.dev", "Pasta de desenvolvimento" },
            { "game.place.usb", "Pendrive / HD externo ({0})" },
            { "game.sizeunknown", "tamanho lido ao instalar" },
            { "game.playedlabel", "TEMPO DE JOGO" },
            { "game.statelabel", "ESTADO" },
            { "game.state.installed", "Instalado" },
            { "game.restart", "Feche e abra o Nativra antes de iniciar outro jogo." },
            { "game.architecture", "Este executável ainda não é compatível. A camada atual aceita apenas jogos Windows x64." },
            { "game.missing", "Os arquivos deste jogo não foram encontrados. Instale-o pela Steam." },
            { "game.launchfailed", "O jogo não iniciou. O diagnóstico foi salvo para investigar a compatibilidade." },
            { "game.state.notinstalled", "Não instalado" },
            { "game.cannotrun.title", "Ainda não dá para abrir" },
            { "game.cannotrun.body", "{0} está baixado no console, mas abrir um executável de Windows aqui depende da camada que ainda estou construindo." },
            { "game.cannotrun.hint", "B para voltar" },
            { "game.failed.title", "O download parou" },
            { "game.failed.hint", "B para voltar. O que já baixou fica, e continuar recomeça de onde parou." },
            { "hint.search", "Buscar" },
            { "hint.options", "Opções" },
            { "steam.shelf.all", "Todos" },
            { "steam.shelf.family", "Família" },
            { "hint.filter", "Filtrar" },
            { "steam.filter.all", "todos" },
            { "steam.filter.downloaded", "baixados" },
            { "steam.shelf.downloaded", "Baixados" },
            { "downloads.title", "Downloads" },
            { "downloads.empty", "Nenhum download nesta sessão. Instale um jogo pela Loja." },
            { "downloads.running", "baixando, {0}%" },
            { "downloads.done", "pronto para jogar" },
            { "downloads.failed", "falhou: {0}" },
            { "downloads.moving", "console cheio, movendo para {0}: {1}" },
            { "steam.downloaded.empty", "Nenhum jogo baixado nesta seleção — volte a todos para instalar um jogo ou ajuste a busca." },
            { "steam.filter.played", "jogados" },
            { "steam.filter.never", "nunca jogados" },
            { "steam.filter.tested", "testados aqui" },
            { "steam.showing", "mostrando {0} de {1}" },
            { "hint.signout", "Sair da conta" },
            { "tile.steam", "Steam" },
            { "tile.steam.sub", "Seus jogos de PC" },
            { "tile.game.sub", "Baixado da Steam" },
            { "status.gamenotyet", "{0} está baixado — falta a camada que executa Windows aqui" },
            { "steam.header", "Steam" },
            { "steam.loading", "carregando sua biblioteca..." },
            { "steam.count", "{0} jogos" },
            { "steam.empty", "nenhum jogo nesta conta" },
            { "steam.failed", "não consegui ler a biblioteca: {0}" },
            { "steam.notyet", "{0} ainda não roda aqui — falta a camada de tradução" },
            { "steam.busy", "já tem um download em andamento" },
            { "steam.starting", "preparando {0}..." },
            { "steam.downloading", "{0} — {1}%  {2}" },
            { "steam.downloading.short", "{0} — {1}%" },
            { "steam.downloaded", "{0} baixado, pronto para jogar" },
            { "steam.downloadfailed", "{0} falhou: {1}" },
            { "steam.nospace", "sem espaço no console: faltam {0} (livre: {1})" },
            { "steam.diskfull", "o disco do console encheu (livre: {0}). Libere espaço e abra o Nativra de novo: o download continua de onde parou" },
            { "steam.signinagain", "A Steam encerrou a sessão. Entre de novo em Loja com o QR code." },
            { "update.downloading", "Baixando a atualização (build {0})…" },
            { "update.installing", "Instalando a atualização (build {0}). O Nativra fecha e volta atualizado." },
            { "update.failed", "Não deu para instalar a atualização (build {0}). Tento de novo na próxima abertura." },
            { "steam.hours", "{0} h jogadas" },
            { "steam.minutes", "{0} min jogados" },
            { "steam.neverplayed", "nunca jogado" },
            { "signin.title", "Entrar na Steam" },
            { "signin.how", "Abra o app Steam no celular, toque no ícone de escanear e aponte para o código ao lado." },
            { "signin.asking", "pedindo o código à Steam..." },
            { "signin.waiting", "esperando você aprovar no celular" },
            { "signin.retry", "tentando de novo ({0})" },
            { "signin.failed", "a Steam não respondeu: {0}" },
            { "signin.qrfailed", "não consegui desenhar o código: {0}" },
            { "signin.expired", "o código expirou — aperte Y para gerar outro" },
            { "signed.title", "Conectado como {0}" },
        };

        private static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            { "setup.title", "Setup" },
            { "setup.inputhint", "Controller mode notice" },
            { "setup.input", "Input mode when opening a game" },
            { "setup.pc", "PC — controller as mouse and keyboard" },
            { "setup.controller", "Native controller — requires game support" },
            { "setup.sensitivity", "Pointer speed (0.25× to 2×)" },
            { "setup.diagnostics", "Show diagnostics over the game" },
            { "setup.on", "On" },
            { "setup.off", "Off" },
            { "setup.save", "Apply" },
            { "setup.cancel", "Cancel" },
            { "setup.applied", "Settings applied." },
            { "setup.failed", "Setup could not open. Try again from the home screen." },
            { "setup.hint", "In PC mode, use the right stick to point and A to click. Hold View + Menu to switch modes during a game. Compatibility is still being tested." },
            { "game.loading", "Starting the game…" },
            { "game.mode.pc", "PC mode · Hold View + Menu for native controller input" },
            { "game.mode.controller", "Controller mode · Hold View + Menu for mouse and keyboard" },
            { "game.loading.hint", "Preparing the compatibility layer. You do not need to press again." },
            { "game.input.hint", "Right stick: mouse · A: click/fire · Left stick: move · Y: jump" },
            { "debug.title", "Nativra {0} · {1} · pre-alpha" },
            { "debug.system", "{0}\nSystem: {1} · {2}" },
            { "debug.gpu", "GPU: {0} · PCI {1}:{2}" },
            { "debug.vram", "Reported VRAM: {0} MiB (not a budget)\nD3D11 · feature level 0x{1}" },
            { "debug.unknown", "not queried" },
            { "debug.render", "Frame: {0}×{1} · D3D11 → CPU → XAML" },
            { "debug.frames", "Present: {0}/s · XAML: {1}/s (not TV FPS)" },
            { "debug.memory", "App memory: {0} / {1} MiB limit" },
            { "debug.input", "UWP gamepads: {0} · XInput reads: {1} · probes: {3}\nKey events: {2}" },
            { "debug.audio.client", "Audio: client acquired; output unverified" },
            { "debug.audio.pending", "Audio: client unavailable · HRESULT 0x{0}" },
            { "debug.sample", "Sample: {0} · 1 s refresh" },
            { "debug.unavailable", "Diagnostics temporarily unavailable" },
            { "app.eyebrow", "IN DEVELOPMENT  \u00B7  BY NSPXMIGUEL" },
            { "tile.allgames", "All games \u00B7 {0}" },
            { "status.notyet", "{0} is not built yet" },
            { "dock.library", "Library" },
            { "emu.add", "Add to library" },
            { "shop.title", "Add systems" },
            { "shop.install", "Install" },
            { "shop.downloading", "Downloading\u2026" },
            { "shop.unpacking", "Unpacking\u2026" },
            { "shop.installing", "Installing\u2026" },
            { "shop.installed", "Installed" },
            { "shop.installed.long", "{0} is installed. It shows among the console's apps; xbdev sync brings it to this screen." },
            { "shop.failed", "Failed: {0}" },
            { "shop.stuck", "Stopped at {0}; see shop-log.txt" },
            { "shop.nopackage", "the download holds no package to install" },
            { "emu.remove", "Remove from library" },
            { "dock.shop", "Shop" },
            { "dock.emulators", "Emulators" },
            { "dock.friends", "Friends" },
            { "dock.mods", "Mods" },
            { "dock.downloads", "Downloads" },
            { "app.title", "Everything installed on this console" },
            { "status.reading", "reading the console..." },
            { "status.count", "{0} installed" },
            { "status.empty", "nothing installed yet — run xbdev kit from the Mac" },
            { "status.opening", "opening {0}..." },
            { "status.refused", "the console refused to open {0}" },
            { "status.failed", "could not open {0}: {1}" },
            { "status.unreadable", "could not read the app list: {0}" },
            { "hint.open", "Open" },
            { "hint.refresh", "Refresh" },
            { "empty.title", "Nothing installed yet" },
            { "empty.next", "Run xbdev sync on the Mac, then press Y here" },
            { "status.noprotocol", "this one opens from Dev Home — it accepts no outside launch" },
            { "hint.back", "Back" },
            { "game.install", "Install" },
            { "game.play", "Play" },
            { "game.cancel", "Cancel" },
            { "game.where", "INSTALL TO" },
            { "game.place.console", "Console" },
            { "game.place.dev", "Developer folder" },
            { "game.place.usb", "USB drive ({0})" },
            { "game.sizeunknown", "size read on install" },
            { "game.playedlabel", "PLAY TIME" },
            { "game.statelabel", "STATE" },
            { "game.state.installed", "Installed" },
            { "game.restart", "Close and reopen Nativra before starting another game." },
            { "game.architecture", "This executable is not supported yet. The current layer only accepts Windows x64 games." },
            { "game.missing", "This game's files were not found. Install it through Steam." },
            { "game.launchfailed", "The game could not start. Diagnostics were saved to investigate compatibility." },
            { "game.state.notinstalled", "Not installed" },
            { "game.cannotrun.title", "It cannot open yet" },
            { "game.cannotrun.body", "{0} is downloaded on the console, but opening a Windows executable here waits on the layer I am still building." },
            { "game.cannotrun.hint", "B to go back" },
            { "game.failed.title", "The download stopped" },
            { "game.failed.hint", "B to go back. What came down stays, and starting again picks up from there." },
            { "hint.search", "Search" },
            { "hint.options", "Options" },
            { "steam.shelf.all", "All" },
            { "steam.shelf.family", "Family" },
            { "hint.filter", "Filter" },
            { "steam.filter.all", "all" },
            { "steam.filter.downloaded", "downloaded" },
            { "steam.shelf.downloaded", "Downloaded" },
            { "downloads.title", "Downloads" },
            { "downloads.empty", "No downloads this session. Install a game from the Shop." },
            { "downloads.running", "downloading, {0}%" },
            { "downloads.done", "ready to play" },
            { "downloads.failed", "failed: {0}" },
            { "downloads.moving", "console full, moving to {0}: {1}" },
            { "steam.downloaded.empty", "No downloaded games in this selection — switch to all to install a game or adjust your search." },
            { "steam.filter.played", "played" },
            { "steam.filter.never", "never played" },
            { "steam.filter.tested", "tested here" },
            { "steam.showing", "showing {0} of {1}" },
            { "hint.signout", "Sign out" },
            { "tile.steam", "Steam" },
            { "tile.steam.sub", "Your PC games" },
            { "tile.game.sub", "Downloaded from Steam" },
            { "status.gamenotyet", "{0} is downloaded — the layer that runs Windows here is still missing" },
            { "steam.header", "Steam" },
            { "steam.loading", "loading your library..." },
            { "steam.count", "{0} games" },
            { "steam.empty", "no games on this account" },
            { "steam.failed", "could not read the library: {0}" },
            { "steam.notyet", "{0} does not run here yet — the translation layer is missing" },
            { "steam.busy", "a download is already running" },
            { "steam.starting", "preparing {0}..." },
            { "steam.downloading", "{0} — {1}%  {2}" },
            { "steam.downloading.short", "{0} — {1}%" },
            { "steam.downloaded", "{0} downloaded, ready to play" },
            { "steam.downloadfailed", "{0} failed: {1}" },
            { "steam.nospace", "not enough space on the console: {0} short ({1} free)" },
            { "steam.diskfull", "the console's disk is full ({0} free). Free some space and open Nativra again: the download picks up where it stopped" },
            { "steam.signinagain", "Steam ended the session. Sign in again from Shop with the QR code." },
            { "update.downloading", "Downloading the update (build {0})…" },
            { "update.installing", "Installing the update (build {0}). Nativra closes and comes back updated." },
            { "update.failed", "Couldn't install the update (build {0}). Trying again next time it opens." },
            { "steam.hours", "{0} h played" },
            { "steam.minutes", "{0} min played" },
            { "steam.neverplayed", "never played" },
            { "signin.title", "Sign in to Steam" },
            { "signin.how", "Open the Steam app on your phone, tap the scan icon and point it at the code." },
            { "signin.asking", "asking Steam for a code..." },
            { "signin.waiting", "waiting for you to approve on your phone" },
            { "signin.retry", "retrying ({0})" },
            { "signin.failed", "Steam did not answer: {0}" },
            { "signin.qrfailed", "could not draw the code: {0}" },
            { "signin.expired", "the code expired — press Y for a new one" },
            { "signed.title", "Signed in as {0}" },
        };

        private static readonly Dictionary<string, string> Active = Pick();

        private static Dictionary<string, string> Pick()
        {
            var forced = System.Environment.GetEnvironmentVariable("KIOSK_LANG");
            if (!string.IsNullOrEmpty(forced))
            {
                return forced.StartsWith("pt") ? Pt : En;
            }
            var language = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
            return language == "pt" ? Pt : En;
        }

        public static string Get(string key, params object[] args)
        {
            if (!Active.TryGetValue(key, out var template) &&
                !En.TryGetValue(key, out template))
            {
                return key;
            }
            return args.Length == 0 ? template : string.Format(template, args);
        }
    }
}
