; Dolphin graphics factory config — written by emulators.ts.

[Settings]
AspectRatio = 0
Crop = False
ShaderCompilationMode = 0
WaitForShadersBeforeStarting = False
InternalResolution = 4
EFBScale = 4
MSAA = 0
SSAA = False
ForceTrueColor = True
DisableCopyFilter = True
ArbitraryMipmapDetection = True
MaxAnisotropy = 4

[Enhancements]
MaxAnisotropy = 4
ForceTrueColor = True
DisableCopyFilter = True

[Hacks]
EFBAccessEnable = True
EFBToTextureEnable = True
EFBScaledCopy = True
BBoxEnable = False
